### ISSUE TITLE
Team Member - Insight Research - Create a Place for Interview Notes, Recordings

### ISSUE THREAD

**Issue by iamjoshfrank** [revelry-foundation/nightingale#11]
### Background
We need a place for in Google Drive for all of our discovery wrap up materials. 

## Scenario: A user creates a G drive 
- [ ] When I navigate to the [Nightingale G Drive](https://drive.google.com/drive/folders/1B8l0uzWR-dekg2qflbfvCPTu2kkT1LaG)
- [ ] then I see a folder for Discovery 
- [ ] And the team can safely move on to conducting a user interview(#27) with a place to capture findings in #12

**Comment by Mcscott142** [comment]
Going to close this. Discovery folder exists and actual discovery work is guided through other issues in https://github.com/revelry-foundation/nightingale/milestone/6
