### ISSUE TITLE
Team Member - Design Studios - Create a Plan for Post-Research Ideation

### ISSUE THREAD

**Issue by iamjoshfrank** [revelry-foundation/nightingale#14]
## Background

Based on the [Customer Research findings (#13)](https://github.com/revelry-foundation/nightingale/issues/13), we can move into an ideation phase to design solutions to agreed-upon problem/opportunity statements.

The **number** of design studios / design thinking exercises / design sprint exercises and the **format** for each should be planned and shared with the team to prepare them for success.

**Comment by Mcscott142** [comment]
Going to close this one. Using #15 to track progress and layout excercises.
