### ISSUE TITLE
DevOps - Hosting - Planning

### ISSUE THREAD

**Issue by vegasgeek** [revelry-foundation/nightingale#18]
## Background

WordPress based projects are hosted, by default, on the Revelry WPEngine account.

This is the first ticket to discuss hosting options with Product Owners as new projects kickoff.

A Product Owner may choose to host the live website on their own account. This would, however, impact development as it relates to continuous integration.

## Scenario: Host on Revelry WPEngine account
Given I am DevOps or a PM
- [ ] When I discuss the Product Owner's current hosting
- [ ] Then I suggest hosting on the Revelry WPEngine account
- [ ] When the Product Owner agrees to host on Revelry WPEngine account
- [ ] Then the PM alerts DevOps that we'll add to the Revelry WPENgine account

## Scenario: Host on Separate Cluster
Given I am DevOps or a PM
- [ ] When I discuss the Product Owner's current hosting
- [ ] Then I suggest hosting on the Revelry WPEngine account
- [ ] When a Product Owner requests their own hosting
- [ ] Then PM alerts DevOps that we need to assess

**Comment by jwietelmann** [comment]
Revelry Labs WPEngine is fine if it speeds up initial delivery.

**Comment by iamjoshfrank** [comment]
Decision (at least for now) was made. It's living on WPEngine currently. Closing.
