### ISSUE TITLE
Developer - Project Setup - Staging Site

### ISSUE THREAD

**Issue by westonmcwhorter** [revelry-foundation/nightingale#22]
## Background
We are now putting all new WordPress projects on the Revelry WPEngine account, unless specified otherwise by the Product Owner. Some Product Owners may choose to use their own hosting as an alternative solution.

Once the production site URL has been determined and the site stood up, we need to add it to the `README.md`.

## Scenario: Add Project to Revelry WPEngine Account
Given I am devops
- [x] When the Product Owner agrees to use Revelry's WPEngine account for hosting
- [x] Then I setup the application dependencies
- [ ] And I give the devs credentials in RPass

## Scenario: Staging Site Active
Given I am a developer
- [x] When the staging site link is active
- [x] Then I add the link to the `README.md` in the relevant links section

**Comment by vegasgeek** [comment]
The staging site has been stood up, but won't be in use until after launch of production site at which time I'll copy the styles/content from production and move it to staging.

The URL is: http://nightingalestg.wpengine.com/

No support login has been created on the site just yet. This ticket can stay open until then.

**Comment by westonmcwhorter** [comment]
As per John's comment above, parking this in `Implement` for the time being.

**Comment by iamjoshfrank** [comment]
@vegasgeek - Are dev credentials in Rpass?

If so, then the rest of this is done. IMHO we should track further work of backporting Production to Staging when we actually "go live."

**Comment by iamjoshfrank** [comment]
No response. Closing.
