### ISSUE TITLE
Developer - Project Setup - Production Site

### ISSUE THREAD

**Issue by westonmcwhorter** [revelry-foundation/nightingale#23]
## Background
We are now putting all new WordPress projects on the Revelry WPEngine account, unless specified otherwise by the Product Owner. Some Product Owners may choose to use their own hosting as an alternative solution.

Once the production site URL has been determined and the site stood up, we need to add it to the `README.md`.

## Scenario: Add Site to Revelry WPEngine Account
Given I am devops
- [x] When the Product Owner agrees to use Revelry's WPEngine account for hosting
- [x] Then I setup the site on WPEngine
- [x] And I give the devs credentials in RPass

## Scenario: Production Site Active
Given I am a developer
- [x] When the production site link is active
- [x] Then I add the link to the `README.md` in the relevant links section

**Comment by vegasgeek** [comment]
The production site is setup and can be found here:
https://nightingaleweb.wpengine.com/

Still waiting for word on what the live URL will be.

I've created a support user account and added it to a Nightingale folder in rPass that has been shared with Wes, Aline, & Laura. I can share with others as needed.

**Comment by westonmcwhorter** [comment]
Pulling through all the way to UAT. Beginning visual design and content work.

**Comment by iamjoshfrank** [comment]
Link added to `README`. Opened #51 re: the domain.
