### ISSUE TITLE
Team - Insight Research - Create a Validation Board

### ISSUE THREAD

**Issue by Mcscott142** [revelry-foundation/nightingale#34]
## Background
Once a team member has conducted an interview, they should be ready to make a list of their core assumptions and risks to be used in the upcoming Design thinking exercises. We can do this using a Validation Board. 

## Scenario: A Team Member creates a Validation board
- [ ] When I have conducted an interview and gone through the debrief (#27 & #12) 
- [ ] Then I create a Validation board (for each interview I participated in) from this [template](https://docs.google.com/spreadsheets/d/1ih9t6cCNgddM-vwEediRvrWp7QaZ1DbxvVQ1FqEWzkM/edit?usp=sharing)
- [ ] And I List of my Core Assumptions from the interview
- [ ] And I List of my Riskiest Assumptions from the interview
- [ ] And I add my board to the [folder in the drive](https://drive.google.com/open?id=1z0Xowzt9Tex0B2fcPNbXZ8Xxvux2iKCL)

**Comment by HauwaAguillard** [comment]
Done with interviews for today. Calling out that this is would be the next step. I've added customer validation to the google drive using the provided template, and I hope to work on it in the morning.
