### ISSUE TITLE
User - Auth - Remove Getting Started and Account Creation

### ISSUE THREAD

**Issue by grossvogel** [revelry-foundation/nightingale#36]
Due to the anonymity of everything, this app won't have any user authentication, so we should remove all of the views and code related to user auth, login, sign-up, etc.

## Scenario: No User Account, No Auth

Given I have downloaded the app
- [x] When I open the app
- [x] Then I am not prompted to create an account
- [x] And I am not prompted to log in to an existing account

**Comment by grossvogel** [comment]
I put revelry-foundation/nightingale-mobile#3 together while working on other mobile app setup.

**Comment by iamjoshfrank** [comment]
@grossvogel - looks like you shipped this work already. I'm moving it all the way ahead to `QA` / `UAT` in preparation of having a testable app ... sometime.

**Comment by iamjoshfrank** [comment]
Since we don't yet have a TestFlight build deployed, I can't perform `UAT`.

Asking another engineer to verify and then close.

**Comment by iamjoshfrank** [comment]
Can an engineer please confirm and close this Issue?

**Comment by DejaTrudeaux** [comment]
@iamjoshfrank Can confirm that there is no prompt to create or log in to an account. Closing

**Comment by iamjoshfrank** [comment]
:thankyou:
