### ISSUE TITLE
App Styleguide 

### ISSUE THREAD

**Issue by CheetoMao** [revelry-foundation/nightingale#38]
We need at least a rough outline of what this app should look like. Sticking with our template parts for faster implementation, I'd like to outline a few aspects of the app design so that we can make sure it's appealing to our audience.

- [x] quick logo treatment with element that can be used for app icon (@westonmcwhorter)
- [ ] colors defined
- [ ] basic type treatment
- [ ] list component (for locations with ability to show/hide/edit)

**Comment by CheetoMao** [comment]
re-Posting high level design direction w/ minor edits [from slack thread here for visibility.](https://revelry-public.slack.com/archives/C014AR56T1P/p1590598224306900?thread_ts=1590595830.293100&cid=C014AR56T1P)

**Start with [Why ahead of making design decisions](https://github.com/revelry-foundation/nightingale/issues/25#issuecomment-634309049)** 

**Build for the audience:** Trusted community leaders and or business owners ([example here](https://www.npr.org/2017/12/22/572583560/joseph-ravenell-could-barbershops-become-the-new-doctors-office)) within underserved/at risk communities and low income areas. 

**Build what matters:** How do I serve my community and or reopen safely?
- **[Accessibility](https://www.w3.org/WAI/standards-guidelines/wcag/)** 
    - We’re asking and this might change _“How do we enable them to serve a community, their community w/ at risk health issues”_ which, at the moment, means creating a design that meets accessibility standards, [including color standards.](http://colorsafe.co/) 
    - **Example;** Asking someone at risk with diabetes who might have eye sight issues and a respiratory condition to report on their status over the phone should/will directly influence your design decisions.
￼
**Design Direction** 
- Clean, simple, and accessible (both in terms of accessibility standards and available devices) 
- Visual Design Examples include; [1](https://help.supply/), [2](https://roo.plannedparenthood.org/onboarding/intro)

**Comment by westonmcwhorter** [comment]
I want to raise my hand here real quick to say that I am going to work on both a LOGO treatment (timeboxing for about an hour or so) and the key visual for the top of the landing page.

**Comment by westonmcwhorter** [comment]
@vegasgeek, here's an option.

![nightingale_logo_v2](https://user-images.githubusercontent.com/45366606/83068701-58625300-a02e-11ea-8704-a518a977ea7d.png)

**Comment by vegasgeek** [comment]
I like it, @westonmcwhorter. Could I get a version with just the bird and the word Nightingale to use for the header bar? The extra text at the bottom will be a bit busy/hard to read in the header.

**Comment by CheetoMao** [comment]
@westonmcwhorter you got that design file on the drive somewhere? Will need the OG file so we can break it up for app icons and whatnot.

**Comment by westonmcwhorter** [comment]
@vegasgeek and @CheetoMao, you got it. Standby.

**Comment by westonmcwhorter** [comment]
Hey, @CheetoMao and @vegasgeek, can find stuff here // https://drive.google.com/open?id=1UuS3yO5MMp7Yzuj4BAZ2sL0MjEro2isu

**Comment by CheetoMao** [comment]
ok here are some quick ideas. Trying to nail down the screens, components, and navigation we'll have. Feedback super welcome as this feels pretty text heavy and not as simple as I'd like for it to be.

**set status**
<img width="539" alt="Screen Shot 2020-05-28 at 12 05 47 PM" src="https://user-images.githubusercontent.com/3287583/83171847-5060ec80-a0dc-11ea-9015-956e584d04c7.png">

**view locations (with map)**
<img width="854" alt="Screen Shot 2020-05-28 at 11 50 23 AM" src="https://user-images.githubusercontent.com/3287583/83171892-62db2600-a0dc-11ea-9313-3bee2f77507b.png">

**view locations (no map)**
<img width="856" alt="Screen Shot 2020-05-28 at 11 51 56 AM" src="https://user-images.githubusercontent.com/3287583/83171929-6c648e00-a0dc-11ea-8628-813bccb22110.png">

**Comment by grossvogel** [comment]
FYI I just merged my PR that has @CheetoMao 's first round of stylesheet changes so that work should be in master

**Comment by iamjoshfrank** [comment]
@CheetoMao - what do you think is left for this Issue vs work that should be split out into new Issues (or addressed as it comes up in the prototype)?

**Comment by CheetoMao** [comment]
I'm gonna go ahead and close this out b/c the styleguide page exists and there are already a few patterns in place. Further design work can be done on specific tickets.
