### ISSUE TITLE
Designer - COVID-19 Status - Quick Wireframe for Symptoms, Test, Test Results

### ISSUE THREAD

**Issue by Mcscott142** [revelry-foundation/nightingale#47]
_related to #42_

## Background
All users are presumed to be negative for COVID-19. The user should be able to edit this default status at any point to share a change in their diagnosis. 

Issue #42 will allow the user to update their COVID-19 status with details of the date when they first experienced symptoms, test date, results date.

Issue #46 will allow a user to share their recent locations to the server.

**The purpose of this issue is to get a quick WireFrame up helping an engineer to handoff #42 and #46 as cleanly as possible to a designer. We shouldn't worry too much about making it perfect. Timebox it for 30 min and just help the engineer with a little direction on the layout.**

### Implementation Notes
- `Negative` = means the user is negative for COVID-19
- `Positive` = means the user is positive for COVID-19
- All users have default of `Negative`
- Let's consider useful help text around the date categories to define what each specifically means

### Desired Outcomes
Once the end user updates their COVID-19 status to `Positive`, the user can also input additional information which will narrow the scope of tracing locations by date to the ~14 days they could have been in contact in various locations. The user should not be urged to input inaccurate dates (eg symptoms), so these inputs should not be required.

## Scenario: A Designer creates a simple WireFrame
- [ ] When I create a Wireframe for an engineer
- [ ] Then I add it as a comment in #42 and #46

**Comment by HauwaAguillard** [comment]
Wires: 

**Onboarding:** 
<img width="432" alt="Screen Shot 2020-05-28 at 5 56 33 PM" src="https://user-images.githubusercontent.com/49654454/83202140-93d34f00-a10c-11ea-8797-4e90e1d3ca23.png">

<img width="555" alt="Screen Shot 2020-05-29 at 9 53 44 AM" src="https://user-images.githubusercontent.com/49654454/83275525-dfc9d680-a194-11ea-9af8-c5209324ee42.png">

<img width="176" alt="Screen Shot 2020-05-29 at 10 08 44 AM" src="https://user-images.githubusercontent.com/49654454/83275537-e22c3080-a194-11ea-9469-72bcc39d3f6d.png">

cc: @iamjoshfrank @grossvogel @CheetoMao @Mcscott142

**Comment by HauwaAguillard** [comment]
I also realize that the ticket ac needed COVID status info only and a symptoms page. I wasn't sure where to put the rest of the screens but needed to get it out in the open. I'll work on another screen for symptoms to account for the entire ac

**Comment by HauwaAguillard** [comment]
Now that I have fully digested the AC lol! I think the wires account for the first sight of COVID symptom date.

<img width="219" alt="Screen Shot 2020-05-29 at 10 38 35 AM" src="https://user-images.githubusercontent.com/49654454/83278102-ab581980-a198-11ea-96f5-68524f1aff18.png">

**Comment by iamjoshfrank** [comment]
Solid. I'll make sure this is referenced on #42 and #46 for our next iteration.
