### ISSUE TITLE
[Bug] Server: Longitude doesn't seem to affect find_proximate_positives results?

### ISSUE THREAD

**Issue by jwietelmann** [revelry-foundation/nightingale#54]
It's Friday, and I don't know why. All I know is that if I insert a positive at lng 90 lat 90 and i search for exactly that:

* It finds the positive (good)
* If I change the lng search param to something far away it still finds the positive (bad)
* If I change the lat search param to something far away it no longer finds the location (good)

**Comment by iamjoshfrank** [comment]
Joel's left the info he discovered. Since this is a bug, I'm not writing a full user story for it. Moving it forward for work this week.

**Comment by iamjoshfrank** [comment]
Even though this is a `bug`, I'm going to play some jazz and say we should put it through Planning Poker so that we have a sense of how it might impact what we can ship this week.

**Comment by jwietelmann** [comment]
HAHAHAHA THERE'S NO BUG MY LATITUDE WAS THE NORTH POLE OF COURSE THE LONGITUDE DOESN'T MATTER.
