### ISSUE TITLE
Reverse Geocoding - Replace Google Places API with a viable solution

### ISSUE THREAD

**Issue by DejaTrudeaux** [revelry-foundation/nightingale#61]
Last week, we left off where we began discussing potential alternatives for the Google Places API as we are going to be making a lot of requests and don't want to run up the bill.  Some ideas we discussed are:

- https://github.com/aaronksaunders/react-native-reverse-geo
- https://github.com/kiwicom/react-native-reverse-geocode
- https://github.com/timwangdev/react-native-geocoder-reborn << Jarrod says this one seems to be the only one that is not outdated, but may be too new for use in production.

The last person to look at switching us over was Jarrod, so whoever picks up this ticket may want to touch base with him briefly to see if there's any previous work we can start with. 

Given I am an engineer
- [ ] When I research alternative reverse geocoding solutions
- [ ] Then I choose one and implement 
- [ ] And remove the Google Places API from the project

**Comment by iamjoshfrank** [comment]
Closing for now. Cost will be free or minimal at this point.
