### ISSUE TITLE
User - COVID Risk Survey - Assist in updating TypeForm 

### ISSUE THREAD

**Issue by Mcscott142** [revelry-foundation/nightingale#62]
## Background
During our Interview with Veena Goud, we learned that we _are_ on the right track with a Risk Assessment tool and a little off-base with a symptom tracker, but we also learned that she is currently attempting to put together a quick Typeform survey to get on the LA Dept of Health website.  

We offered our assistance in getting the correct logic tied into the Typeform so they can quickly get a stop-gap solution in the short term while we continue to evaluate and design a tool under the nightingale umbrella. 

The Typeform survey currently lives in its current state [here](https://scott142908.typeform.com/to/tl3kdg). 

We'll use this issue to help track any assistance we provide Veena and call in reinforcements if need be around getting the survey live etc. 

### Resources
[Typeform survey](https://scott142908.typeform.com/to/tl3kdg)
[Similar App from John Hopkins](https://www.hopkinsmedicine.org/coronavirus/covid-19-self-checker.html)

## Scenario: A user can complete the Typeform Survey and get a true risk assessment
- [ ] When I fill out this [survey](https://scott142908.typeform.com/to/tl3kdg)
- [ ] Then I receive my personal risk assessment

**Comment by Mcscott142** [comment]
Marking this as Blocked. Veena has requested @BenRongey and @Mcscott142 added to the Typeform Survey. We'll have a quick call with Veena to get direction after that.

**Comment by Mcscott142** [comment]
The meeting w/ Veena scheduled for 10am this morning. @BenRongey and @Mcscott142 both have access to Typeform quiz now. Unblocking.

**Comment by Mcscott142** [comment]
We are sprucing up this [Public Survey](https://scott142908.typeform.com/to/tl3kdg), to have logic that gives users the end results of whether they are high/medium/low risk. We have an opportunity to quickly put this together and get it in front of several key decision-makers. 

Had call w/ Veena, adding notes at the bottom of this comment. We have access to the Typeform and Ben is running with getting the logic where it needs to be. Once the logic is there, we'll do another content run through with Veena. 

**If we can get this accomplished today, in the right hands of Veena's contacts, they may be able to promote it at the Governor's press conference tomorrow.**

Going to #firedrill that last piece since we may want some content love in here for a few specific pages. 

I can get document edit access to whoever needs it or I can share my credentials via Keybase to get whoever needs to be in. 

cc @jeremybrady 

Notes from the call
-----
### General Notes

- Italy hit hard because of multi-generational households
- Germany nuclear families - not as badly hit
- Lots of nuclear families in US BUT maybe Communities, which have multigenerational households are being hit the hardest. 
- Overweight, Smoking, and Household risks are HUGE. 
- Tightness in chest, heavy Breathing -> go to the hospital
- Possible avenues for exposure to survey
	- Dept of health site
	- dept of public health site
	- back to work safely website
	- governors text alerts

### Typeform specific
Q5 Updated Language needed
>Do you have any of the following health conditions: immunocompromised condition?This question is required.

Q8 - C or D (Overweight, Obese) Flag for high risk

Q9 
50 or younger - Low Risk
50 or older - Medium to High
65 older High Risk


Q12 - do you interact with unfamiliar 

Low-risk message - We need better low-risk message content. Not "You are low risk", more "Your risk is slightly lower", you are still vulnerable etc. It looks like you are still at risk for getting COVID-19 but lower risk harsher symptoms/more dangerous disease.

FAQ's need to be laid out in a much better format. 

Medium Risk - Anyone who they themselves are low risk but someone in their household is high risk

On the opening page we need to Credit Scott Teesdale, Veena's health dept @ LSU, and Revelry (foundation?):

>Done in partnership with the LDH and Revelry(foundation?), Scott Teesdale consulting, Center for Healthcare Value and Equity, LSU School of Medicine

## Next Steps
- [ ] Make the Logic for the survey is work
- [ ] Work with Veena to Update Content (pull in some design help?)
- [ ] Someone from Rev email to the group Veena has shared via email. Veena will work back channels to press conference. 

Via email from Veena: 
>Once we have a working tool it needs to go to these people to be put on the OPH webpage and *hopefully* it can be highlighted in the press conference tomorrow (wed 6/3). Scott, do you think it should go to the whole list below or just the first 4 names?

**Comment by BenRongey** [comment]
@Mcscott142  the point for the Revelry Labs/Foundation logo might be irrelevant.  From what I've found (so far), only one image can be added per each slide/question.  If that's the case then obviously we'll go with the Louisiana Department of Health logo.

**Comment by Mcscott142** [comment]
We'll figure something out. Maybe just list the names we need to w/o logos on page 1 and provide links to "partners" on the FAQ or something. Maybe that defeats the purpose of this. Thinking out loud.

**Comment by Mcscott142** [comment]
@BenRongey I'm going to email Veena to walk through the Survey w/ the Logic we have and see what updates she wants. Will include the question around number 11 or 13 (depending). 

One thing I noticed, even if a User is a High Risk, we'll want to follow up with the FAQ's screen, I went through a couple of times and it was only happening for Low Risk.

**Comment by Mcscott142** [comment]
Notes from Feedback session
## Survey Feedback
#5 better explainer here? 
#9 add 0-15?
#11 what do we need there?
We lost our FAQ's

Veena Feedback: 
#9
- Change ages to 1-20, 20-30, 30-40, 40-50, 50-60
    - 50 and up is High Risk
- Leave in "Have you been Tested?" This is an anonymous Survey. 
- #12 drop it
**To Add**
- Have you had Symptoms of COVID-19
    - No 
    - Yes
    - Select All Symptoms that apply
        - Run through NYT article
        - Flag difficulty of breathing or tightness of chest
    - #11 Check all that apply
        - 
#13 Replace w . symptom check
    - Have you had any symptoms of the COVID-19 disease 

Drop 17
Q#18 How many people live in household (share bathrooms and/or kitchen) Flag @ greater than 4

Q#20 Medium to High if you say yes
Q#19 Multi Select - do you have a childcare or >monthly contact with anyone that has

Change high-risk message
Flag MEdium 

For email
>Let us know if we can get this accessible on a Website before moving to phase 2

Zoom Chat copy pasta
From Veena Goud to Everyone: (3:17 PM)
 question 9: add 1-15 1-20 20-30 30-40 40-50 50-65 65+ 
From Veena Goud to Everyone: (3:23 PM)
 q10 this is anonymous and your answer can not be linked to you add question have you had symptoms of covid 19 no fever cough GI/stomach issues loss of smell fatigue/ tiredmess foggy brain difficulty breathing (out of breath when walking) tightness in chest 
From Veena Goud to Everyone: (3:28 PM)
 breath - if you or anyone answer you know has this symptom please call your doctor remove antibody test question Q11 check all that apply 
From Veena Goud to Everyone: (3:35 PM)
 q 16 visit a lot of places where you interact with many people who may or may not have covid-19 drop q17 q18 H over 65 or live in a multigenerational houshold 
From Veena Goud to Everyone: (3:42 PM)
 Q18 add (share a bathroom or kitchen) Q18 How many live in household (share bathrooms and/or kitchen) 18 flag at >4 agg a q do you have a with same as 19 
From Veena Goud to Everyone: (3:49 PM)
 do you have a childcare or >monthly contact with anyone that has

**Comment by Mcscott142** [comment]
Final(ish) survey: https://scott142908.typeform.com/to/YWNtvZ.

**Comment by iamjoshfrank** [comment]
Still sitting in `Estimate`, maybe b/c we skipped that step but didn't click the skip button?

In any case, seems like this can be closed @Mcscott142 ?

**Comment by Mcscott142** [comment]
Re-opening for some changes and tracking my work here. Email from Veena:

>The big issue is checking that the logic for the high risk and the low risk works correctly.

>Few updates from Scott:
>A few updates I wanted to suggest:
>- I updated my name to Teesdale Design; I honestly would also be fine removing the attributions or tossing them at the end… 
>- When you go to the CDC website for BMI; it bounces you back to a question about doctors taking your BMI… I would have expected it to go to a question on; well hey now that you have an estimate from the cdc tool; put it here. 
>- in step 2 or 3 - you write out hypertension (hy-per-ten-shun) with a phonetic spelling; but none of the other medical terms have it.  I would just remove it - and focus on common terms vernacular.  
>- The common best practices presents outside of the flow after it presents like its ending.  I would inject it up a few steps and keep it within the tool flow.

**Comment by Mcscott142** [comment]
Done. Seems like it's working: https://scott142908.typeform.com/to/YWNtvZ. Closing this again.
