### ISSUE TITLE
Designer - COVID Risk Survey - create image for Typeform Survey Final Page

### ISSUE THREAD

**Issue by Mcscott142** [revelry-foundation/nightingale#71]
## Background 
We have #62 in getting a quick turn around Typeform survey done in hopes of getting it on the LA dept of public health website this week. We are getting very close to wrapping that up, but it could use a few tweaks. 

The survey can be taken [here](https://scott142908.typeform.com/to/ahomH1) in its current state.

The most important one being that at the end of the Survey, we have a general list of 10 steps to battle COVID, but they don't look very appealing and there isn't much we can do style-wise on only one survey slide in Typeform. @BenRongey suggested that we create an image for them and just upload the image to the page. 

We're hoping to enlist someone a quick image we can upload to the end of the survey, that makes the list more appealing and readable. 

<details>
<summary>Details</summary>

![Fullscreen_6_2_20__4_19_PM](https://user-images.githubusercontent.com/6877299/83571263-11240880-a4ed-11ea-82b9-5fe557d210b1.png)

</details>

## Scenario: A user completes their survey
- [ ] When I complete the survey
- [ ] Then I see an image of 10 basic steps to fight COVID

**Comment by Mcscott142** [comment]
## Text form of the  10 tips. 

<details>
<summary>10 Tips</summary>

Here are ten basic things that everyone should be doing all the time, starting today:

1. Wash your hands often with soap and warm water, rubbing all parts of your hands for 20 seconds (especially after you cough, sneeze or blow your nose). When you can’t wash your hands, use an alcohol-based hand sanitizer. If you can’t find any hand sanitizer in stores, make your own using this recipe.
2. Put alcohol-based hand sanitizer by the front door of your home and in your car. Try to make it a regular habit to have each person in your household use it each time they go in or out of the house or car.
3. Bump knuckles or elbows in public instead of shaking hands.
4. Avoid contact with high-touch surfaces in public places, such as doorknobs and handles, handrails, shopping cart handles, elevator buttons, light switches, and public transport seats. Use your elbow (or a gloved hand) to open doors.
5. Cover your coughs and sneezes with a tissue, your sleeve or your elbow.
6. Try not to touch your face, especially your eyes, nose, and mouth (unless you wash your hands first).
7. Avoid close contact with people who are sick (especially if they are sneezing, coughing, or have runny noses).
8. Avoid crowds, especially in closed, indoor spaces. Limit unnecessary travel and contact.
9. Regularly clean and disinfect your home to remove germs, especially on high-touch surfaces with disinfecting wipes or a solution of bleach and water. Wiping surfaces such as doorknobs, light switches, handles, toilets, faucets, cell phones, countertops and steering wheels once a day is recommended (more if someone in your household is sick).
10. If you feel sick, take your temperature with a thermometer and stay home. Don’t go to work or school. Call your doctor, report your symptoms and ask for advice. Do not go to the emergency room or urgent care center unless it is an emergency. If you find you are having trouble breathing, have chest pain or have sudden confusion, don’t wait, call for help and dial 9-1-1.
</details>

**Comment by HauwaAguillard** [comment]
@Mcscott142 @BenRongey here is a screenshot let me know if this works

<img width="451" alt="Screen Shot 2020-06-02 at 5 57 41 PM" src="https://user-images.githubusercontent.com/49654454/83577713-906c0900-a4fa-11ea-8569-9b5ee4c807cd.png">

**Comment by Mcscott142** [comment]
@HauwaAguillard I think this works for our purposes. can you share the file with @BenRongey so he can see how it looks in the Typeform?

**Comment by HauwaAguillard** [comment]
Do we know what size we are looking for? 

P.S. I'm gonna push up what I have for now in a folder though and share here in a sec

**Comment by HauwaAguillard** [comment]
@BenRongey uploaded image can be found here: https://drive.google.com/drive/folders/1f1F_PYxRsMyWw0CZmZu3QJwopUqMx8VT

**Comment by BenRongey** [comment]
@Mcscott142 I don't think this is going to work very well.  The image is automatically centered and it ends up a lil small.

**Comment by HauwaAguillard** [comment]
Want to pair so we can figure out the right size?

**Comment by Mcscott142** [comment]
It's totally ok if it doesn't work. Don't want y'all to expend too much effort on this.

**Comment by HauwaAguillard** [comment]
**Update:** 
Paired with @BenRongey and doesn't look like adding an image to the survey final page would work. However, we decided to go with what is currently there and added some spaces between each todo which should help improve the readability.

I'm tempted to close this ticket out as I consider this done, however, I shall move this to UAT and assign to @Mcscott142
