### ISSUE TITLE
Images Needed for Publication - Screenshots, Wires/Mocks

### ISSUE THREAD

**Issue by iamjoshfrank** [revelry-foundation/nightingale#74]
@HauwaAguillard and/or someone from engineering discipline to support if needed:

Today, we'll likely be publishing several posts about our efforts to-date. I have a recap article I've written about last week's efforts that you can find here: [Nightingale - Track A Summary for Publication](https://docs.google.com/document/d/1I0j4TQPb6A9HdbgtN_302jhypNHAQnwZVtQy0nPYeRo/edit).

Take a look at the article draft and if you would, please grab some of the following and drop them into comments below:

- screenshots of the related screens
- wires/mocks if you think they'd be helpful
- maybe even some screenshots of related GitHub Issues

For reference, you can see Jeremy's draft article here: [Draft: Working on stuff that matters](https://docs.google.com/document/d/1xj2FKhRMRDuF0qDZa26recB8vCpjMSvXk7Lsx14xHbs/edit?usp=sharing)

My assumption is you can look to @gerardramos or @jeremybrady for direction/clarification on this task, but I'd like you to try to take ownership of this and grab things first if at all possible.

I'll be offline / AFK (Away From Keyboard) until at least 9:30am Central today.

**Comment by HauwaAguillard** [comment]
@iamjoshfrank I've added most of the screens to google drive needed for the publication. 

Here is the file structure: 
- Screenshots can be found in `Nightingale > Make > Assets > Track A - Screens`
- While in `Track A - Screens`, you'll notice I've uploaded wires and created two folders, 
    -  App screenshots 
    - GitHub milestone screens

let me know if you need anything else

**Comment by iamjoshfrank** [comment]
Closing. I'm now tracking the follow-up efforts in a [Revelry content Issue.](https://github.com/revelrylabs/content/issues/965)
