### ISSUE TITLE
Team Member - Insight Research - Develop Interview Pool 

### ISSUE THREAD

**Issue by iamjoshfrank** [revelry-foundation/nightingale#8]
## Background
We need to leverage our networks to develop an interview pool of Epidemiologists, Mental health workers, community leaders, and community business owners. We want 1:1 connections so that trust has already been established and we can quickly schedule and conduct the interviews for insight. 

Again, the list of individuals we are looking for are as follows, 1:1 relationships with 
- Epis
- Mental health workers
- PPE creators
- Community Leaders
- Community Business owners

The Customer pool will be put together based on this Review Design Challenge Question:
>How might we identify and enable through the direction of public health officials, trusted contact tracers within the community with the means to securely and anonymously identify those with COVID-19?

## Scenario: The team creates a list of Contacts to schedule interviews with
- [ ] When I have identified a contact 
- [ ] Then I add them to the [Customer Pool Spreadsheet](https://docs.google.com/spreadsheets/d/1pkg82J_Lx45qy2x-xrEukeAi3o6t3_ORu_ejn89wcCc/edit?usp=sharing) 
**Don't share this pool outside of Revelry for privacy reasons.**
- [ ] Then I can move on to #9

**Comment by thomasknoll** [comment]
I believe @jeremybrady has an initial list identified. I am assuming we can still seek out more.

**Comment by jeremybrady** [comment]
Yes. [Here](https://docs.google.com/spreadsheets/d/1pkg82J_Lx45qy2x-xrEukeAi3o6t3_ORu_ejn89wcCc/edit?usp=sharing) 

*Don't share this pool outside of Revelry for privacy reasons.

Pool is cross-section of
- Epis
- Mental health workers
- PPE creators
- Community Leaders
- Community Business owners

CC @iamjoshfrank for visibility

**Comment by iamjoshfrank** [comment]
Closed because the list is complete and there's no further work to do on it?

Or accidentally closed upon comment?

**Comment by jeremybrady** [comment]
>Or accidentally closed upon comment?

Oops, that.

**Comment by HauwaAguillard** [comment]
@jeremybrady added Dr. Murelle G. Harrison, Executive Director of the Gardere Initiative, and Prof. at Southern University to the list. She would be a good contact person for South Baton Rouge. She is also a licensed Industrial/Organizational Psychologist, not sure if to categorize her under mental health worker or community leader but she is both

**Comment by thomasknoll** [comment]
quick update to clarify: I don't really have good networks to add more folks to the list, so I can either grab some folks and run some of my own interviews, or join someone else as a note taker. I am 100% onboard for working through the next steps with the information we learn from these interviews.

**Comment by alinelea** [comment]
[Slack thread](https://revelry-public.slack.com/archives/C014AR56T1P/p1590516751113600)

**Comment by HauwaAguillard** [comment]
@jeremybrady I see we've added 👇 to the email template

> [E.R. nurses & doctors ](https://github.com/revelry-foundation/nightingale/issues/9#issuecomment-634213006)

Would that be a user group to be added here?

**Comment by westonmcwhorter** [comment]
I have some friends in the mental health space. Would that be a good cohort to include in our outreach?

**Comment by brittneybrown** [comment]
i have a friend in hospital admin who is heading up the covid response at an integris hospital in OKC. is this someone we may want to interview?

**Comment by BenRongey** [comment]
It shouldn't necessarily be ER people.  As this has expanded the majority of work has gone from the ER to the ICUs.  In fact the ER in NOLA is super slow the past few weeks.  This should read something like `Critical Care nurses & doctors` to reflect both ICU/Covid wards && ERs/EDs.

**Comment by brittneybrown** [comment]
> i have a friend in hospital admin who is heading up the covid response at an integris hospital in OKC. is this someone we may want to interview?

i asked and she agreed, so i'm just going to put her on the sheet.

**Comment by jeremybrady** [comment]
Hi team, I love the energy around this, so firstly thank you for your additions. To help funnel our efforts a couple asks for ya'll 

At this point we're specifically looking for;
1. 2-3 Community leaders within Louisiana that you ideally have a 1:1 connection with
2. 2 Mental health workers within Louisiana that you ideally have a 1:1 connection with

Thanks in advance.

**Comment by Mcscott142** [comment]
I'm going through and closing things that I believe to be complete. Feel free to re-open and tell me to stop. I'm starting with this one.
