### ISSUE TITLE
Weird Beeps

### ISSUE THREAD

**Issue by DejaTrudeaux** [revelry-foundation/nightingale#82]
I just noticed some things when logging into the app on Testflight for the first time that did not happen when running locally. One concern is that when you click Covid19 Hotspots, two beeps happen every so often, and I feel like that could potentially scare a user.

As an engineer:
- [ ] When I find out the cause for the two beeps
- [ ] Then I remove them

**Comment by Samkeer1** [comment]
That's 'debug: true' in LocationListener.tsx.

<img width="461" alt="Screen Shot 2020-06-05 at 10 22 45 AM" src="https://user-images.githubusercontent.com/43652523/83894124-80c90c00-a716-11ea-80ef-01d30665547c.png">

**Comment by DejaTrudeaux** [comment]
@Samkeer1 ahhh i see, do we want that? if so, closing!

**Comment by Samkeer1** [comment]
Nope, it's super annoying and I usually keep it set to false when I'm running movement simulations. We can close this, I'll commit 'debug: false' into what i'm working on currently which is #58
