### ISSUE TITLE
Team Member - Insight Research - Schedule Customer Interviews

### ISSUE THREAD

**Issue by iamjoshfrank** [revelry-foundation/nightingale#9]
## Background
Once we have identified all of the candidates in #8, we need to divide and conquer to schedule interviews and mark them as scheduled. 

As for related issues, we have #25 for framing the design challenge question and #10 for laying out the interview script. Those can be worked in parallel with this issue, they just need to be ready by the time we conduct the interviews.  

## Scenario: The team schedules interviews with their respective candidates
- [ ] When I have scheduled an interview with my contact (use this [template](https://github.com/revelry-foundation/nightingale/issues/9#issuecomment-634213006) for the invite)
- [ ] And I have also recruited a note taker
- [ ] Then I update the status of that person in the [Contact Pool spreadsheet](https://docs.google.com/spreadsheets/d/1pkg82J_Lx45qy2x-xrEukeAi3o6t3_ORu_ejn89wcCc/edit#gid=0)
- [ ] And you can move on to #27

**Comment by jeremybrady** [comment]
Hi contact's first name,

Hope this note finds you well.

My name is x and I work at [Revelry.co](http://revelry.co/), a design and development firm based here in New Orleans. 

We need your help to influence the creation of a contact tracing tool directed by the Louisiana Department of Health. We’re specifically looking to develop a better way for people to share their COVID-19 status safely and anonymously in a new free open source product. 

And we’re looking to gather insight from a cross section of epidemiologists, psychiatrists, E.R. nurses & doctors, community leaders and community members within Louisiana.

Therefore I’d like to ask you some questions 1:1 over the phone that will help us to develop the concepts for a contact tracing tool. Your feedback will directly influence our design ideas. 

If you’re interested and have 60 minutes to chat (I promise to keep the time!), reply back to this email with your choice of the times below that work for you. I’ll follow up with you to figure out what method is the best way for us to connect.

- Day, Month 00⋅0:00 – 0:00 am/pm
- Day, Month 00⋅0:00 – 0:00 am/pm
- Day, Month 00⋅0:00 – 0:00 am/pm

Thanks for helping us.

Stay safe and healthy,
Your first name

-- 

Your name
Your title
Revelry Labs
[Revelry.co](http://revelry.co/)

**Comment by HauwaAguillard** [comment]
@jeremybrady do we send out the meeting invite along with this [Design Research Participant Agreement](https://docs.google.com/document/d/1iYeAvAwK7_t2Cez-QH-HdrDs1ANImaF3X5Qz0-T9gZs/edit) ? do the participants have to sign it first?

**Comment by jeremybrady** [comment]
Optional and leaving that decision up to people on a case to case basis.

**Comment by Mcscott142** [comment]
Closing, re-open if need be.
