### ISSUE TITLE
Discovery - App Comparisons - Safepaths vs COVID Shield

### ISSUE THREAD

**Issue by Mcscott142** [revelry-foundation/nightingale#94]
## Background
There are 2 competing Applications widely adopted for Contact Tracing right now. Safepaths and COVID Shield. Both are open source and may be utilized in an effort to push forward the questions below. 

>1.	Are there any comparative advantages when comparing COVID Shield and COVID Safe-Paths from a product and design perspective; focusing on the 18 to 25-year-old student demographic in Louisiana. In particular: Specifically; 
a.	How can we best promote the adoption and uptake of an exposure notification app?
b.	How can we best promote positive behavior change when you get a notification to isolate, get tested, talk to a contact tracer.

We need to do a look into the respective Codebases and capture some documentation around the technology and make a recommendation based on the technical specs. 

https://safepaths.mit.edu/
https://www.covidshield.app/

## Scenario: An engineer does a Code Review on Safepaths
- [ ] When I research safepaths
- [ ] Then I document my findings

## Scenario: An engineer does a Code Review on COVID Shield
- [ ] When I research COVID Shield
- [ ] Then I document my findings

## Scenario: An engineer recommends an App based on comparison
- [ ] When I have completed the first 2 scenarios
- [ ] Then I make a recommendation on which is more technically sound

**Comment by jrotolo** [comment]
Picking up this ticket now.

**Comment by Mcscott142** [comment]
@jrotolo any updates here?

**Comment by Mcscott142** [comment]
Will drop additional notes but it's sounding like path check is the way to go. https://pathcheck.org/
