### ISSUE TITLE
Discovery - Reactive Contact Tracing - Frame the Question

### ISSUE THREAD

**Issue by Mcscott142** [revelry-foundation/nightingale#96]

**Comment by jeremybrady** [comment]
**Design Challenge:** 
How might we best optimize the 30-50 mins we have someone, during testing, too;
- Better phone number veracity
- Nudge cases to get in touch with contacts - share status (I’m Sick); get them to sign up for symptom monitoring or something like this… 
- Nudge people to wear masks better, stay away from people (better social distancing)
- Start the process for them to do contact tracing (Maybe a worksheet) 

CC @Mcscott142 @HauwaAguillard @maryolivier

**Comment by Mcscott142** [comment]
Added to #95. Closing this one.
