### ISSUE TITLE
Discovery - Reactive Contact Tracing - Interview Scipt

### ISSUE THREAD

**Issue by Mcscott142** [revelry-foundation/nightingale#97]
## Background 

TBD

[Old Script to build from](https://docs.google.com/document/d/1r1qexqqn8mP9OnBhvPbwscKRMdfWCgXkq9BGkGCT1wQ/edit)

**Comment by jeremybrady** [comment]
[Creating new script here](https://docs.google.com/document/d/1r1qexqqn8mP9OnBhvPbwscKRMdfWCgXkq9BGkGCT1wQ/edit?usp=sharing) for [personas/customer pool outlined in our customer pool.](https://docs.google.com/spreadsheets/d/1zkMj0S19d8wnnAykLMDFo5GmarVNoYSFJYo3udKDF4U/edit?usp=sharing)

CC @Mcscott142 @HauwaAguillard @maryolivier @bmccrossen

**Comment by Mcscott142** [comment]
Moved to LDH Repo
https://github.com/revelrylabs/LDH/issues/2
https://github.com/revelrylabs/LDH/issues/3
